Repository apache/cordova-android, pull requests merged in 2019-07, with the labels that each got.

#765 ci(travis): Fix Android SDK
  .travis.yml
Labels: bug

#782 Do not clobber console.log to spy on it
  spec/unit/android_sdk.spec.js
  spec/unit/run.spec.js
Labels: bug

#783 Do not clobber process properties with test mocks
  spec/unit/run.spec.js
Labels: bug

#784 Properly handle promise in create script
  bin/lib/create.js
  spec/unit/create.spec.js
Labels: bug

#787 Simplify and fix promise handling in specs
  spec/unit/Api.spec.js
  spec/unit/check_reqs.spec.js
  spec/unit/create.spec.js
Labels: bug, enhancement

#788 Simplify apkSorter using compare-func package
  bin/templates/cordova/lib/builders/ProjectBuilder.js
  package.json
  spec/unit/builders/ProjectBuilder.spec.js
Labels: enhancement
