Repository apache/cordova-android, pull requests merged in 2020-07, with the labels that each got.

#1012 test: fix missing stack traces in jasmine output
  spec/helper.js
Labels: bug

#1017 test(java): fix, improve and move clean script
  package.json
  test/clean.js
Labels: bug, enhancement

#1015 Remove unnecessary stuff
  LICENSE
  bin/lib/create.js
  bin/lib/utils.js
  bin/templates/cordova/lib/check_reqs.js
  spec/e2e/helpers/projectActions.js
  spec/unit/create.spec.js
Labels: enhancement

#1016 refactor: save ProjectBuilder instance in Api instance
  bin/templates/cordova/Api.js
  bin/templates/cordova/lib/build.js
  bin/templates/cordova/lib/run.js
  spec/unit/Api.spec.js
  spec/unit/run.spec.js
Labels: enhancement

#1013 test(pluginHandlers/common): better setup & teardown
  spec/unit/pluginHandlers/common.spec.js
Labels: bug

#1014 fix(pluginHandlers): properly check if path is inside another
  bin/templates/cordova/lib/pluginHandlers.js
  package-lock.json
  package.json
  spec/unit/pluginHandlers/common.spec.js
Labels: bug

#1019 chore: remove unused emulator.create_image and local dependencies
  bin/templates/cordova/lib/emulator.js
Labels: enhancement

#975 ci: Added Node 14.x
  .github/workflows/ci.yml
Labels: enhancement
