Repository apache/cordova-android, pull requests merged in 2021-07, with the labels that each got.

#1138 feat(allow-list): integrate and refactor core plugin
  bin/templates/project/assets/www/index.html
  bin/templates/project/res/xml/config.xml
  framework/src/org/apache/cordova/AllowList.java
  framework/src/org/apache/cordova/AllowListPlugin.java
  framework/src/org/apache/cordova/Config.java
  framework/src/org/apache/cordova/ConfigXmlParser.java
  framework/src/org/apache/cordova/CordovaWebView.java
  framework/src/org/apache/cordova/CordovaWebViewImpl.java
  framework/src/org/apache/cordova/allowlist/index.html
  framework/src/org/apache/cordova/allowlist/index2.html
  framework/src/org/apache/cordova/engine/SystemWebViewClient.java
  test/androidx/app/src/main/assets/www/allowlist/index.html
  test/androidx/app/src/main/assets/www/allowlist/index2.html
  test/androidx/app/src/main/assets/www/index.html
Labels: enhancement

#1212 feat!: unify & fix gradle library/tooling overrides
  .gitignore
  bin/lib/create.js
  bin/templates/cordova/lib/builders/ProjectBuilder.js
  bin/templates/cordova/lib/check_reqs.js
  bin/templates/cordova/lib/gradle-config-defaults.js
  bin/templates/cordova/lib/plugin-build.gradle
  bin/templates/cordova/lib/prepare.js
  bin/templates/project/app/build.gradle
  bin/templates/project/build.gradle
  framework/build.gradle
  framework/cdv-gradle-config-defaults.json
  framework/cordova.gradle
  framework/default.properties
  framework/gradle/wrapper/gradle-wrapper.properties
  framework/project.properties
  spec/e2e/plugin.spec.js
  spec/unit/check_reqs.spec.js
  spec/unit/prepare.spec.js
  test/androidx/app/build.gradle
  test/androidx/build.gradle
  test/androidx/wrapper.gradle
  test/run_java_unit_tests.js
Labels: bug

#1259 tests(prepare): factor out common vars
  spec/unit/prepare.spec.js
Labels: enhancement

#1260 refactor(check_reqs): drop originalError param from check_android_target
  bin/templates/cordova/lib/builders/ProjectBuilder.js
  bin/templates/cordova/lib/check_reqs.js
  spec/unit/builders/ProjectBuilder.spec.js
Labels: enhancement

#1100 refactor!: remove most platform binaries
  README.md
  bin/android_sdk_version
  bin/android_sdk_version.bat
  bin/check_reqs
  bin/check_reqs.bat
  bin/create
  bin/create.bat
  bin/lib/create.js
  bin/templates/cordova/android_sdk_version
  bin/templates/cordova/build
  bin/templates/cordova/build.bat
  bin/templates/cordova/clean
  bin/templates/cordova/clean.bat
  bin/templates/cordova/lib/build.js
  bin/templates/cordova/lib/install-device.bat
  bin/templates/cordova/lib/install-emulator
  bin/templates/cordova/lib/install-emulator.bat
  bin/templates/cordova/lib/list-devices.bat
  bin/templates/cordova/lib/list-emulator-images.bat
  bin/templates/cordova/lib/list-started-emulators
  bin/templates/cordova/lib/list-started-emulators.bat
  bin/templates/cordova/lib/log.js
  bin/templates/cordova/lib/run.js
  bin/templates/cordova/lib/start-emulator
  bin/templates/cordova/lib/start-emulator.bat
  bin/templates/cordova/log
  bin/templates/cordova/log.bat
  bin/templates/cordova/loggingHelper.js
  bin/templates/cordova/run
  bin/templates/cordova/run.bat
  bin/templates/cordova/version.bat
  bin/update
  bin/update.bat
  package.json
  spec/e2e/plugin.spec.js
  spec/unit/run.spec.js
Labels: enhancement

#1263 test(check_reqs): do not hardcode DEFAULT_TARGET_API
  spec/unit/check_reqs.spec.js
Labels: enhancement

#1264 fix: missing super.onRequestPermissionsResult error (MissingSuperCall)
  framework/src/org/apache/cordova/CordovaActivity.java
Labels: bug

#1266 refactor(run)!: cleanup run method
  bin/templates/cordova/lib/run.js
  spec/unit/run.spec.js
Labels: enhancement

#1267 refactor: use target SDK of built APK to determine best emulator
  bin/templates/cordova/lib/emulator.js
  bin/templates/cordova/lib/run.js
  bin/templates/cordova/lib/target.js
  spec/unit/emulator.spec.js
  spec/unit/run.spec.js
  spec/unit/target.spec.js
Labels: enhancement

#563 fix(build): support tilde expansion on windows
  lib/build.js
  package-lock.json
  package.json
Labels: bug

#1270 refactor(Api)!: use version from package.json
  lib/Api.js
Labels: enhancement

#1216 fix: request focus after custom view hided
  framework/src/org/apache/cordova/CordovaWebViewImpl.java
Labels: bug

#1276 fix: remove forced default gradle.daemon setting
  lib/config/GradlePropertiesParser.js
Labels: bug

#1271 build: build cordova.js during npm prepare
  .gitignore
  .npmignore
  lib/create.js
  package-lock.json
  package.json
  templates/project/assets/www/cordova.js
  test/androidx/app/src/main/assets/www/cordova.js
  test/run_java_unit_tests.js
Labels: enhancement

#1278 chore!: drop node 10 support
  .github/workflows/ci.yml
  package.json
Labels: enhancement

#1279 chore!: bump all dependencies
  package-lock.json
  package.json
Labels: enhancement

#1283 fix: add missing apache-license header to getASPath.bat
  lib/getASPath.bat
Labels: bug

#1287 fix: Google Services Gradle Plugin version check failure
  templates/project/app/build.gradle
Labels: bug

#1294 fix: automatic latest build tools finding
  framework/cordova.gradle
Labels: bug

#1293 fix: gradle build tools config
  framework/cdv-gradle-config-defaults.json
  framework/cordova.gradle
  templates/project/app/build.gradle
Labels: bug

#1295 fix: maven-publish setup
  framework/cordova-publish.gradle
Labels: enhancement

#1301 chore: bump version 10.1.0-dev
  framework/src/org/apache/cordova/CordovaWebView.java
  package-lock.json
  package.json
Labels: enhancement

#1298 feat: support http w/ content src fix
  framework/src/org/apache/cordova/ConfigXmlParser.java
Labels: bug, enhancement
