Repository apache/cordova-android, pull requests merged in 2023-04, with the labels that each got.

#1587 dep: bump npm dependencies
  lib/build.js
  lib/check_reqs.js
  lib/prepare.js
  package-lock.json
  package.json
Labels: dependencies

#1471 fix!: ANDROID_HOME is the new default, to check first and give advice
  framework/cordova.gradle
  lib/check_reqs.js
  spec/unit/check_reqs.spec.js
Labels: enhancement

#1539 feat!: bump Gradle 7.6 & AGP 7.4.2
  framework/AndroidManifest.xml
  framework/build.gradle
  framework/cdv-gradle-config-defaults.json
  framework/cordova.gradle
  lib/AndroidManifest.js
  lib/AndroidProject.js
  lib/builders/ProjectBuilder.js
  lib/config/CordovaGradleConfigParser.js
  lib/config/CordovaGradleConfigParserFactory.js
  lib/create.js
  lib/prepare.js
  lib/run.js
  lib/target.js
  spec/fixtures/android_studio_project/gradle/wrapper/gradle-wrapper.properties
  spec/unit/AndroidManifest.spec.js
  spec/unit/AndroidProject.spec.js
  spec/unit/builders/ProjectBuilder.spec.js
  spec/unit/create.spec.js
  spec/unit/mocks/config/MockCordovaGradleConfigParser.js
  spec/unit/pluginHandlers/handlers.spec.js
  spec/unit/prepare.spec.js
  spec/unit/run.spec.js
  spec/unit/target.spec.js
  templates/project/AndroidManifest.xml
  templates/project/app/build.gradle
Labels: enhancement

#1606 fix: Gradle Args parsing
  lib/build.js
  lib/builders/ProjectBuilder.js
  package-lock.json
  package.json
  spec/unit/build.spec.js
  spec/unit/builders/ProjectBuilder.spec.js
Labels: bug
